### ISSUE TITLE
Deduplication chunking algorithm with dmdedup

### ISSUE THREAD

**Issue by alfal85** [dmdedup/dmdedup#16]
Hi there
Currently I'm working on deduplication project. my goal is to use dmdeduplication solution to compare different chunking algorithms with the fixed chunking (that is used by dm-deduplication).

To do so, I would like to integrate different algorithms with the dmdeduplication module. I was trying to find where the dmdeduplication is doing the fixed chunking in order to replace that part with the different algorithms with no luck :(
Can anyone tell me what is the right file that I should look into to handle this.

Thanks

**Comment by sectorsize512** [comment]
Hey,

Dmdedup currently supports only fixed chunking. The chunking is performed by device-mapper subsystem (not by Dmdedup itself). Instead, Dmdedup uses dm_set_target_max_io_len() utility function to set maximum I/O to 4KB (see dm-dedup-target.c file), informing device-mapper to chop I/O in 4KB units (or larger, if asked by the user).

Supporting variable chunking in an inline deduplication (like Dmdedup) is not an easy task. Many things would need to change in Dmdedup's code, IMHO. You can start from looking into process_bio() function in dm-dedup-target.c - this is where the I/O is seen for the first time by the Dmdedup worker thread. This function (and the functions it calls) expect fixed chunks. You need to change the logic so that variable chunks are supported.

HTH

**Comment by alfal85** [comment]
Thanx a lot for the valuable response and suggestions.
Appreciate it.
